### ISSUE TITLE
Error when running node command

### ISSUE THREAD

**Issue by arch0345** [ideditor/nsi-collector#6]
When running `node collect_osm.js /path/to/filtered.osm.pbf` I get this error:
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'osmium'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/c/Users/<user>/OneDrive/Documents/GitHub/ideditor/nsi-collector/collect_osm.js:14:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by arch0345** [comment]
Does node-pre-gyp need to be a certain version as well or is this dependent on the node version being used? Looking at the error messages I'm using v0.10.3

**Comment by bhousel** [comment]
That's what I have too:
```
% npm ls node-pre-gyp
@ideditor/nsi-collector@1.0.20210919 /Users/bryan/Projects/nsi-collector
└─┬ osmium@0.5.7
  └── node-pre-gyp@0.10.3
```

node-pre-gyp will try to download a compiled binary from s3 that matches your `{node_abi}-{platform}-{arch}.tar.gz` environment, and luckily for me node 10, darwin, and x86 happens to work 😬   .. If it doesn't find a precompiled binary, It will fall back to compiling from source, and then good luck.
